# Trainer
max_epochs: 5
accumulate_grad_batches: 128
val_check_interval: 0.1

# Model
model_name: google/pegasus-large
max_input_length: 1024
max_output_length: 256
learning_rate: None
#1e-4

# Data
train_dataset: data/coqa/coqa-train-v1.0.json
val_dataset: data/coqa/coqa-dev-v1.0.json
batch_size: 2
