# Model
model_name: google/pegasus-large
max_input_length: 1024
max_output_length: 256

# Data
data_name: qrecc
train_dataset: 
val_dataset: 
test_dataset: data/qrecc/scai-qrecc21-test-questions-rewritten.json
#test_dataset: data/qrecc/scai-qrecc21-toy-questions.json
passages: data/qrecc/passages-index-anserini
max_history: 3
max_candidates: 3
max_workers: 24
batch_size: 3
cache_dataset: true
